apiVersion: apps/v1
kind: Deployment
metadata:
  name: emmanuel-services
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: emmanuel-services
  template:
    metadata:
      labels:
        app: emmanuel-services
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
