# File: helm/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emmanuel-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: emmanuel.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emmanuel-services
                port:
                  number: 80
